[tool.poetry]
name = "pandoc-run-python"
version = "0.1.0"
description = "run python code blocks in markdown code"
authors = ["Bart Smeets"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
panflute = "^2.0.5"
black = "^21.5b1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[tool.poetry.scripts]
pandoc-run-python = "pandoc_run_python.pandoc_run_python:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
